spring.application.name=phonebook
spring.datasource.url=jdbc:h2:mem:local_phonebook
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=none
spring.h2.console.enabled=true
spring.sql.init.mode=always
application.working-dir-path=C:/Users/user/Desktop/File_System/Programming/0_Bevezeto/Phonebook2.0/Phonebook
