spring.application.name=phonebook
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=master;encrypt=true;trustServerCertificate=true;integratedSecurity=true
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always