spring.application.name=live
spring.datasource.url= jdbc:sqlserver://localhost:1433;database=master;encrypt=true;trustServerCertificate=true;integratedSecurity=true
spring.datasource.driverClassName= com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect