name: Automatic Versioning

on:
  push:

jobs:
  versioning:
    runs-on: ubuntu-latest
    env:
      ENTERPRISE_REPO: "https://github.com/Kesmarki-Dev/Enterprise.git"

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Get current version and branch
        id: vars
        run: |
          cd Phonebook
          echo "VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT
          echo "name=branch::$(mvn -q -Dexec.executable=echo -Dexec.args='${GITHUB_REF##*/}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT


      - name: Show extracted Maven project version and branch
        run: |
          echo Original version $VERSION
          echo Currnet branch ${{ steps.vars.outputs.branch }}
